return {
	close = "",
	modified = "",
	hint = "", -- ""
	info = "",
	warning = "",
	error = "",
	git = {

	},
	files = {
		default = "", -- 
		symlink = "",
		zip = "",
		img = "",
	},
	folders = {

		default = "",
		open = "",
		empty = "",
		empty_open = "",
		symlink = "",
	},
	debug = {
		error = "",
		warn = "",
		info = "",
		debug = "",
		trace = "",
	},
}


-- local icons = {
--   rounded_left_filled = '',
--   rounded_right_filled = '',
--   arrow_left_filled = '', -- e0b2
--   arrow_right_filled = '', -- e0b0
--   arrow_left = '', -- e0b3
--   arrow_right = '', -- e0b1
--   ghost = '',
--   cosmic = '💫',
--   star = '★',
--   scorpio = '♏︎',
--   rocket = '🚀',
--   warn = '',
--   info = '',
--   error = '',
--   hint = '',
--   perf = ' ',
--   note = '',
--   branch = '',
--   file = '',
--   dotdotdot = '…',
--   information = '',
--   symlink = '',
--   line_number = '',
--   debug = ' ',
--   flame = ' ',
--   check = ' ',
--   trace = '✎',
--   file1 = '',
--   file2 = '',
--   clock = '',
--   word = '',
--   diff_add = ' ',
--   diff_modified = ' ',
--   diff_remove = ' ',
--   git = {
--     unstaged = '✗',
--     staged = '✓',
--     unmerged = '',
--     renamed = '➜',
--     untracked = '★',
--     deleted = '',
--     ignored = '◌',
--   },
--   folder = {
--     arrow_open = '',
--     arrow_closed = '',
--     default = '',
--     open = '',
--     empty = '',
--     empty_open = '',
--     symlink = '',
--     symlink_open = '',
--   },
--   kind_icons = {
--     Text = '',
--     Method = 'm',
--     Function = '',
--     Constructor = '',
--     Field = '',
--     Variable = '',
--     Class = '',
--     Interface = '',
--     Module = '',
--     Property = '',
--     Unit = '',
--     Value = '',
--     Enum = '',
--     Keyword = '',
--     Snippet = '',
--     Color = '',
--     File = '',
--     Reference = '',
--     Folder = '',
--     EnumMember = '',
--     Constant = '',
--     Struct = '',
--     Event = '',
--     Operator = '',
--     TypeParameter = '',
--   },
-- }



-- return {
-- 	kind = {
-- 		Text = "",
-- 		-- Method = "m",
-- 		-- Function = "",
-- 		-- Constructor = "",
-- 		Method = "",
-- 		Function = "",
-- 		Constructor = "",
-- 		Field = "",
-- 		-- Variable = "",
-- 		Variable = "",
-- 		Class = "",
-- 		Interface = "",
-- 		-- Module = "",
-- 		Module = "",
-- 		Property = "",
-- 		Unit = "",
-- 		Value = "",
-- 		Enum = "",
-- 		-- Keyword = "",
-- 		Keyword = "",
-- 		-- Snippet = "",
-- 		Snippet = "",
-- 		Color = "",
-- 		File = "",
-- 		Reference = "",
-- 		Folder = "",
-- 		EnumMember = "",
-- 		Constant = "",
-- 		Struct = "",
-- 		Event = "",
-- 		Operator = "",
-- 		TypeParameter = "",
-- 	},
-- 	type = {
-- 		Array = "",
-- 		Number = "",
-- 		String = "",
-- 		Boolean = "蘒",
-- 		Object = "",
-- 	},
-- 	documents = {
-- 		File = "",
-- 		Files = "",
-- 		Folder = "",
-- 		OpenFolder = "",
-- 	},
-- 	git = {
-- 		Add = "",
-- 		Mod = "",
-- 		Remove = "",
-- 		Ignore = "",
-- 		Rename = "",
-- 		Diff = "",
-- 		Repo = "",
-- 	},
-- 	ui = {
-- 		Lock = "",
-- 		Circle = "",
-- 		BigCircle = "",
-- 		BigUnfilledCircle = "",
-- 		Close = "",
-- 		NewFile = "",
-- 		Search = "",
-- 		Lightbulb = "",
-- 		Project = "",
-- 		Dashboard = "",
-- 		History = "",
-- 		Comment = "",
-- 		Bug = "",
-- 		Code = "",
-- 		Telescope = "",
-- 		Gear = "",
-- 		Package = "",
-- 		List = "",
-- 		SignIn = "",
-- 		Check = "",
-- 		Fire = "",
-- 		Note = "",
-- 		BookMark = "",
-- 		Pencil = "",
-- 		-- ChevronRight = "",
-- 		ChevronRight = ">",
-- 		Table = "",
-- 		Calendar = "",
-- 	},
-- 	diagnostics = {
-- 		Error = "",
-- 		Warning = "",
-- 		Information = "",
-- 		Question = "",
-- 		Hint = "",
-- 	},
-- 	misc = {
-- 		Robot = "ﮧ",
-- 		Squirrel = "",
-- 		Tag = "",
-- 		Watch = "",
-- 	},
-- }
